title: Michael Pham # your name (or website title) here
logo: "/images/MichaelPham.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm Michael and I am a junior developer and student at Momentum Learning, Inc. My passions involve mentoring youth, education, and software development.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/phamm89/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
